name: Run eslint and npm publish dry-run 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run Eslint
      run: make lint
      
    - name: Run publish dry-run
      run: npm publish --dry-run
