name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: make test

    - name: Test & publish code coverage
      #   # Publish code coverage on Code Climate
      #   # https://github.com/paambaati/codeclimate-action
    - uses: paambaati/codeclimate-action@v3
      #   # Add Code Climate secret key
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_COVERAGE_SECRET }}
      with:
          coverageCommand: make test-coverage
          debug: true

